// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1944327631;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__blend_utils__blend_pixel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "blend_pixel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dst = <u32>::sse_decode(&mut deserializer);
            let api_src = <u32>::sse_decode(&mut deserializer);
            let api_mode = <crate::api::blend_utils::BlendMode>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::blend_utils::blend_pixel(
                        api_dst, api_src, api_mode,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__blend_utils__composite_region_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "composite_region",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_width = <i32>::sse_decode(&mut deserializer);
            let api_height = <i32>::sse_decode(&mut deserializer);
            let api_layers_pixels = <Vec<Vec<u32>>>::sse_decode(&mut deserializer);
            let api_layers_opacity = <Vec<f64>>::sse_decode(&mut deserializer);
            let api_layers_blend_mode =
                <Vec<crate::api::blend_utils::BlendMode>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::blend_utils::composite_region(
                    api_width,
                    api_height,
                    api_layers_pixels,
                    api_layers_opacity,
                    api_layers_blend_mode,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for crate::api::blend_utils::BlendMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::blend_utils::BlendMode::Normal,
            1 => crate::api::blend_utils::BlendMode::Multiply,
            2 => crate::api::blend_utils::BlendMode::Dissolve,
            3 => crate::api::blend_utils::BlendMode::Darken,
            4 => crate::api::blend_utils::BlendMode::ColorBurn,
            5 => crate::api::blend_utils::BlendMode::LinearBurn,
            6 => crate::api::blend_utils::BlendMode::DarkerColor,
            7 => crate::api::blend_utils::BlendMode::Lighten,
            8 => crate::api::blend_utils::BlendMode::Screen,
            9 => crate::api::blend_utils::BlendMode::ColorDodge,
            10 => crate::api::blend_utils::BlendMode::LinearDodge,
            11 => crate::api::blend_utils::BlendMode::LighterColor,
            12 => crate::api::blend_utils::BlendMode::Overlay,
            13 => crate::api::blend_utils::BlendMode::SoftLight,
            14 => crate::api::blend_utils::BlendMode::HardLight,
            15 => crate::api::blend_utils::BlendMode::VividLight,
            16 => crate::api::blend_utils::BlendMode::LinearLight,
            17 => crate::api::blend_utils::BlendMode::PinLight,
            18 => crate::api::blend_utils::BlendMode::HardMix,
            19 => crate::api::blend_utils::BlendMode::Difference,
            20 => crate::api::blend_utils::BlendMode::Exclusion,
            21 => crate::api::blend_utils::BlendMode::Subtract,
            22 => crate::api::blend_utils::BlendMode::Divide,
            23 => crate::api::blend_utils::BlendMode::Hue,
            24 => crate::api::blend_utils::BlendMode::Saturation,
            25 => crate::api::blend_utils::BlendMode::Color,
            26 => crate::api::blend_utils::BlendMode::Luminosity,
            _ => unreachable!("Invalid variant for BlendMode: {}", inner),
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::blend_utils::BlendMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::blend_utils::BlendMode>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Vec<u32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<Vec<u32>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__blend_utils__blend_pixel_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__blend_utils__composite_region_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::blend_utils::BlendMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Normal => 0.into_dart(),
            Self::Multiply => 1.into_dart(),
            Self::Dissolve => 2.into_dart(),
            Self::Darken => 3.into_dart(),
            Self::ColorBurn => 4.into_dart(),
            Self::LinearBurn => 5.into_dart(),
            Self::DarkerColor => 6.into_dart(),
            Self::Lighten => 7.into_dart(),
            Self::Screen => 8.into_dart(),
            Self::ColorDodge => 9.into_dart(),
            Self::LinearDodge => 10.into_dart(),
            Self::LighterColor => 11.into_dart(),
            Self::Overlay => 12.into_dart(),
            Self::SoftLight => 13.into_dart(),
            Self::HardLight => 14.into_dart(),
            Self::VividLight => 15.into_dart(),
            Self::LinearLight => 16.into_dart(),
            Self::PinLight => 17.into_dart(),
            Self::HardMix => 18.into_dart(),
            Self::Difference => 19.into_dart(),
            Self::Exclusion => 20.into_dart(),
            Self::Subtract => 21.into_dart(),
            Self::Divide => 22.into_dart(),
            Self::Hue => 23.into_dart(),
            Self::Saturation => 24.into_dart(),
            Self::Color => 25.into_dart(),
            Self::Luminosity => 26.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::blend_utils::BlendMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::blend_utils::BlendMode>
    for crate::api::blend_utils::BlendMode
{
    fn into_into_dart(self) -> crate::api::blend_utils::BlendMode {
        self
    }
}

impl SseEncode for crate::api::blend_utils::BlendMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::blend_utils::BlendMode::Normal => 0,
                crate::api::blend_utils::BlendMode::Multiply => 1,
                crate::api::blend_utils::BlendMode::Dissolve => 2,
                crate::api::blend_utils::BlendMode::Darken => 3,
                crate::api::blend_utils::BlendMode::ColorBurn => 4,
                crate::api::blend_utils::BlendMode::LinearBurn => 5,
                crate::api::blend_utils::BlendMode::DarkerColor => 6,
                crate::api::blend_utils::BlendMode::Lighten => 7,
                crate::api::blend_utils::BlendMode::Screen => 8,
                crate::api::blend_utils::BlendMode::ColorDodge => 9,
                crate::api::blend_utils::BlendMode::LinearDodge => 10,
                crate::api::blend_utils::BlendMode::LighterColor => 11,
                crate::api::blend_utils::BlendMode::Overlay => 12,
                crate::api::blend_utils::BlendMode::SoftLight => 13,
                crate::api::blend_utils::BlendMode::HardLight => 14,
                crate::api::blend_utils::BlendMode::VividLight => 15,
                crate::api::blend_utils::BlendMode::LinearLight => 16,
                crate::api::blend_utils::BlendMode::PinLight => 17,
                crate::api::blend_utils::BlendMode::HardMix => 18,
                crate::api::blend_utils::BlendMode::Difference => 19,
                crate::api::blend_utils::BlendMode::Exclusion => 20,
                crate::api::blend_utils::BlendMode::Subtract => 21,
                crate::api::blend_utils::BlendMode::Divide => 22,
                crate::api::blend_utils::BlendMode::Hue => 23,
                crate::api::blend_utils::BlendMode::Saturation => 24,
                crate::api::blend_utils::BlendMode::Color => 25,
                crate::api::blend_utils::BlendMode::Luminosity => 26,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::blend_utils::BlendMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::blend_utils::BlendMode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Vec<u32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<u32>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
