// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<int> blendPixel({
  required int dst,
  required int src,
  required BlendMode mode,
}) => RustLib.instance.api.crateApiBlendUtilsBlendPixel(
  dst: dst,
  src: src,
  mode: mode,
);

Uint32List compositeRegion({
  required int width,
  required int height,
  required List<Uint32List> layersPixels,
  required List<double> layersOpacity,
  required List<BlendMode> layersBlendMode,
}) => RustLib.instance.api.crateApiBlendUtilsCompositeRegion(
  width: width,
  height: height,
  layersPixels: layersPixels,
  layersOpacity: layersOpacity,
  layersBlendMode: layersBlendMode,
);

enum BlendMode {
  normal,
  multiply,
  dissolve,
  darken,
  colorBurn,
  linearBurn,
  darkerColor,
  lighten,
  screen,
  colorDodge,
  linearDodge,
  lighterColor,
  overlay,
  softLight,
  hardLight,
  vividLight,
  linearLight,
  pinLight,
  hardMix,
  difference,
  exclusion,
  subtract,
  divide,
  hue,
  saturation,
  color,
  luminosity,
}
