// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_to_u64`, `parse_engine_points`, `parse_spray_points`, `pump_engine_if_needed`

Future<bool> canvasEngineInit() =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEngineInit();

Future<PlatformInt64> canvasEngineCreate({
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineCreate(
  width: width,
  height: height,
);

Future<void> canvasEngineDispose({required PlatformInt64 handle}) => RustLib
    .instance
    .api
    .crateApiCanvasEngineCanvasEngineDispose(handle: handle);

Future<void> canvasEngineAttachPresent({
  required PlatformInt64 handle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineAttachPresent(
  handle: handle,
  width: width,
  height: height,
);

Future<bool> canvasEnginePollFrameReady({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEnginePollFrameReady(
      handle: handle,
    );

Future<Uint8List?> canvasEngineReadPresent({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEngineReadPresent(
      handle: handle,
    );

Future<void> canvasEnginePushPointsPacked({
  required PlatformInt64 handle,
  required List<int> bytes,
  required BigInt pointCount,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEnginePushPointsPacked(
  handle: handle,
  bytes: bytes,
  pointCount: pointCount,
);

Future<PlatformInt64> canvasEngineGetInputQueueLen({
  required PlatformInt64 handle,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineGetInputQueueLen(
  handle: handle,
);

Future<void> canvasEngineSetActiveLayer({
  required PlatformInt64 handle,
  required int layerIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetActiveLayer(
  handle: handle,
  layerIndex: layerIndex,
);

Future<void> canvasEngineSetLayerOpacity({
  required PlatformInt64 handle,
  required int layerIndex,
  required double opacity,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetLayerOpacity(
  handle: handle,
  layerIndex: layerIndex,
  opacity: opacity,
);

Future<void> canvasEngineSetLayerVisible({
  required PlatformInt64 handle,
  required int layerIndex,
  required bool visible,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetLayerVisible(
  handle: handle,
  layerIndex: layerIndex,
  visible: visible,
);

Future<void> canvasEngineSetLayerClippingMask({
  required PlatformInt64 handle,
  required int layerIndex,
  required bool clippingMask,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetLayerClippingMask(
  handle: handle,
  layerIndex: layerIndex,
  clippingMask: clippingMask,
);

Future<void> canvasEngineSetLayerBlendMode({
  required PlatformInt64 handle,
  required int layerIndex,
  required int blendModeIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetLayerBlendMode(
  handle: handle,
  layerIndex: layerIndex,
  blendModeIndex: blendModeIndex,
);

Future<void> canvasEngineReorderLayer({
  required PlatformInt64 handle,
  required int fromIndex,
  required int toIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineReorderLayer(
  handle: handle,
  fromIndex: fromIndex,
  toIndex: toIndex,
);

Future<void> canvasEngineSetViewFlags({
  required PlatformInt64 handle,
  required int viewFlags,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetViewFlags(
  handle: handle,
  viewFlags: viewFlags,
);

Future<void> canvasEngineClearLayer({
  required PlatformInt64 handle,
  required int layerIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineClearLayer(
  handle: handle,
  layerIndex: layerIndex,
);

Future<void> canvasEngineFillLayer({
  required PlatformInt64 handle,
  required int layerIndex,
  required int colorArgb,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineFillLayer(
  handle: handle,
  layerIndex: layerIndex,
  colorArgb: colorArgb,
);

Future<bool> canvasEngineBucketFill({
  required PlatformInt64 handle,
  required int layerIndex,
  required int startX,
  required int startY,
  required int colorArgb,
  required bool contiguous,
  required bool sampleAllLayers,
  required int tolerance,
  required int fillGap,
  required int antialiasLevel,
  required List<int> swallowColors,
  Uint8List? selectionMask,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineBucketFill(
  handle: handle,
  layerIndex: layerIndex,
  startX: startX,
  startY: startY,
  colorArgb: colorArgb,
  contiguous: contiguous,
  sampleAllLayers: sampleAllLayers,
  tolerance: tolerance,
  fillGap: fillGap,
  antialiasLevel: antialiasLevel,
  swallowColors: swallowColors,
  selectionMask: selectionMask,
);

Future<Uint8List?> canvasEngineMagicWandMask({
  required PlatformInt64 handle,
  required int layerIndex,
  required int startX,
  required int startY,
  required bool sampleAllLayers,
  required int tolerance,
  Uint8List? selectionMask,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineMagicWandMask(
  handle: handle,
  layerIndex: layerIndex,
  startX: startX,
  startY: startY,
  sampleAllLayers: sampleAllLayers,
  tolerance: tolerance,
  selectionMask: selectionMask,
);

Future<Uint32List?> canvasEngineReadLayer({
  required PlatformInt64 handle,
  required int layerIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineReadLayer(
  handle: handle,
  layerIndex: layerIndex,
);

Future<Uint8List?> canvasEngineReadLayerPreview({
  required PlatformInt64 handle,
  required int layerIndex,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineReadLayerPreview(
  handle: handle,
  layerIndex: layerIndex,
  width: width,
  height: height,
);

Future<bool> canvasEngineWriteLayer({
  required PlatformInt64 handle,
  required int layerIndex,
  required List<int> pixels,
  required bool recordUndo,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineWriteLayer(
  handle: handle,
  layerIndex: layerIndex,
  pixels: pixels,
  recordUndo: recordUndo,
);

Future<bool> canvasEngineTranslateLayer({
  required PlatformInt64 handle,
  required int layerIndex,
  required int deltaX,
  required int deltaY,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineTranslateLayer(
  handle: handle,
  layerIndex: layerIndex,
  deltaX: deltaX,
  deltaY: deltaY,
);

Future<bool> canvasEngineSetLayerTransformPreview({
  required PlatformInt64 handle,
  required int layerIndex,
  required List<double> matrix,
  required bool enabled,
  required bool bilinear,
}) => RustLib.instance.api
    .crateApiCanvasEngineCanvasEngineSetLayerTransformPreview(
      handle: handle,
      layerIndex: layerIndex,
      matrix: matrix,
      enabled: enabled,
      bilinear: bilinear,
    );

Future<bool> canvasEngineApplyLayerTransform({
  required PlatformInt64 handle,
  required int layerIndex,
  required List<double> matrix,
  required bool bilinear,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineApplyLayerTransform(
  handle: handle,
  layerIndex: layerIndex,
  matrix: matrix,
  bilinear: bilinear,
);

Future<Int32List?> canvasEngineGetLayerBounds({
  required PlatformInt64 handle,
  required int layerIndex,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineGetLayerBounds(
  handle: handle,
  layerIndex: layerIndex,
);

Future<void> canvasEngineSetSelectionMask({
  required PlatformInt64 handle,
  Uint8List? selectionMask,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetSelectionMask(
  handle: handle,
  selectionMask: selectionMask,
);

Future<void> canvasEngineResetCanvas({
  required PlatformInt64 handle,
  required int backgroundColorArgb,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineResetCanvas(
  handle: handle,
  backgroundColorArgb: backgroundColorArgb,
);

Future<void> canvasEngineResetCanvasWithLayers({
  required PlatformInt64 handle,
  required int layerCount,
  required int backgroundColorArgb,
}) =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEngineResetCanvasWithLayers(
      handle: handle,
      layerCount: layerCount,
      backgroundColorArgb: backgroundColorArgb,
    );

Future<bool> canvasEngineResizeCanvas({
  required PlatformInt64 handle,
  required int width,
  required int height,
  required int layerCount,
  required int backgroundColorArgb,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineResizeCanvas(
  handle: handle,
  width: width,
  height: height,
  layerCount: layerCount,
  backgroundColorArgb: backgroundColorArgb,
);

Future<void> canvasEngineUndo({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEngineUndo(handle: handle);

Future<void> canvasEngineRedo({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiCanvasEngineCanvasEngineRedo(handle: handle);

Future<void> canvasEngineSetBrush({
  required PlatformInt64 handle,
  required int colorArgb,
  required double baseRadius,
  required bool usePressure,
  required bool erase,
  required int antialiasLevel,
  required int brushShape,
  required bool randomRotation,
  required int rotationSeed,
  required double spacing,
  required double hardness,
  required double flow,
  required double scatter,
  required double rotationJitter,
  required bool snapToPixel,
  required bool hollowEnabled,
  required double hollowRatio,
  required bool hollowEraseOccluded,
  required double streamlineStrength,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSetBrush(
  handle: handle,
  colorArgb: colorArgb,
  baseRadius: baseRadius,
  usePressure: usePressure,
  erase: erase,
  antialiasLevel: antialiasLevel,
  brushShape: brushShape,
  randomRotation: randomRotation,
  rotationSeed: rotationSeed,
  spacing: spacing,
  hardness: hardness,
  flow: flow,
  scatter: scatter,
  rotationJitter: rotationJitter,
  snapToPixel: snapToPixel,
  hollowEnabled: hollowEnabled,
  hollowRatio: hollowRatio,
  hollowEraseOccluded: hollowEraseOccluded,
  streamlineStrength: streamlineStrength,
);

Future<void> canvasEngineSprayBegin({required PlatformInt64 handle}) => RustLib
    .instance
    .api
    .crateApiCanvasEngineCanvasEngineSprayBegin(handle: handle);

Future<void> canvasEngineSprayDraw({
  required PlatformInt64 handle,
  required List<double> points,
  required BigInt pointCount,
  required int colorArgb,
  required int brushShape,
  required bool erase,
  required int antialiasLevel,
  required double softness,
  required bool accumulate,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineSprayDraw(
  handle: handle,
  points: points,
  pointCount: pointCount,
  colorArgb: colorArgb,
  brushShape: brushShape,
  erase: erase,
  antialiasLevel: antialiasLevel,
  softness: softness,
  accumulate: accumulate,
);

Future<void> canvasEngineSprayEnd({required PlatformInt64 handle}) => RustLib
    .instance
    .api
    .crateApiCanvasEngineCanvasEngineSprayEnd(handle: handle);

Future<bool> canvasEngineApplyFilter({
  required PlatformInt64 handle,
  required int layerIndex,
  required int filterType,
  required double param0,
  required double param1,
  required double param2,
  required double param3,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineApplyFilter(
  handle: handle,
  layerIndex: layerIndex,
  filterType: filterType,
  param0: param0,
  param1: param1,
  param2: param2,
  param3: param3,
);

Future<bool> canvasEngineApplyAntialias({
  required PlatformInt64 handle,
  required int layerIndex,
  required int level,
}) => RustLib.instance.api.crateApiCanvasEngineCanvasEngineApplyAntialias(
  handle: handle,
  layerIndex: layerIndex,
  level: level,
);
